install.packages(c("ggplot2",
                   "raster",
                   "grid",
                   "scales",
                   "extrafont",
                   "wesanderson",
                   "ggthemes",
                   "plotKML",
                   "R.utils",
                   "dplyr",
                   "reshape2",
                    "RODBC",
                    "remotes"),
                 dep = TRUE)
